services:
  customer-service:
    build: ./customer-service
    ports:
      - "8001:8000"
    environment:
      - DB_NAME=${CUSTOMER_DB}
      - MONGO_URI=${MONGO_URI}
  book-service:
    build: ./book-service
    ports:
      - "8002:8000"
    environment:
      - DB_NAME=${BOOK_DB}
      - MONGO_URI=${MONGO_URI}
  cart-service:
    build: ./cart-service
    ports:
      - "8003:8000"
    environment:
      - DB_NAME=${CART_DB}
      - MONGO_URI=${MONGO_URI}
  staff-service:
    build: ./staff-service
    ports:
      - "8004:8000"
    environment:
      - DB_NAME=${STAFF_DB}
      - MONGO_URI=${MONGO_URI}
  manager-service:
    build: ./manager-service
    ports:
      - "8005:8000"
    environment:
      - DB_NAME=${MANAGER_DB}
      - MONGO_URI=${MONGO_URI}
  catalog-service:
    build: ./catalog-service
    ports:
      - "8006:8000"
    environment:
      - DB_NAME=${CATALOG_DB}
      - MONGO_URI=${MONGO_URI}
  order-service:
    build: ./order-service
    ports:
      - "8007:8000"
    environment:
      - DB_NAME=${ORDER_DB}
      - MONGO_URI=${MONGO_URI}
  ship-service:
    build: ./ship-service
    ports:
      - "8008:8000"
    environment:
      - DB_NAME=${SHIP_DB}
      - MONGO_URI=${MONGO_URI}
  pay-service:
    build: ./pay-service
    ports:
      - "8009:8000"
    environment:
      - DB_NAME=${PAY_DB}
      - MONGO_URI=${MONGO_URI}
  comment-rate-service:
    build: ./comment-rate-service
    ports:
      - "8010:8000"
    environment:
      - DB_NAME=${COMMENT_DB}
      - MONGO_URI=${MONGO_URI}
  recommender-ai-service:
    build: ./recommender-ai-service
    ports:
      - "8011:8000"
    environment:
      - DB_NAME=${RECOMMENDER_DB}
      - MONGO_URI=${MONGO_URI}
  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=${GATEWAY_DB}
      - MONGO_URI=${MONGO_URI}
    volumes:
      - ./api-gateway:/app
