CREATE DATABASE IF NOT EXISTS customer_db;
CREATE DATABASE IF NOT EXISTS book_db;
CREATE DATABASE IF NOT EXISTS cart_db;
CREATE DATABASE IF NOT EXISTS order_db;
CREATE DATABASE IF NOT EXISTS gateway_db;

GRANT ALL PRIVILEGES ON customer_db.* TO 'user'@'%';
GRANT ALL PRIVILEGES ON book_db.* TO 'user'@'%';
GRANT ALL PRIVILEGES ON cart_db.* TO 'user'@'%';
GRANT ALL PRIVILEGES ON order_db.* TO 'user'@'%';
GRANT ALL PRIVILEGES ON gateway_db.* TO 'user'@'%';
FLUSH PRIVILEGES;
